let database = {
    dewasa: [
        {
            id : 1,
            judul: "The Girl who Fell Beneath the Sea",
            sinopsis: 'Badai mematikan telah merusak tanah kelahiran Mina selama beberapa generasi. Banjir menyapu seluruh desa, sementara perang berdarah dikobarkan untuk memperebutkan sumber daya yang tersisa. Masyarakat di desa Mina memercayai bahwa Dewa Laut mengutuk mereka dengan kematian dan keputusasaan. Dalam upaya untuk menenangkan Dewa Laut, setiap tahun seorang gadis cantik dibuang ke laut untuk menjadi pengantin Dewa Laut, dengan harapan suatu hari pengantin sejati akan dipilih dan mengakhiri penderitaan mereka. Shim Cheong adalah gadis tercantik di desa, sekaligus kekasih Joon. Banyak yang percaya dialah pengantin sejati Dewa Laut Tapi pada malam Cheong hendak dikorbankan, Joon mengikuti Cheong, meski tahu bahwa ikut campur akan dihadiahi hukuman mati. Untuk menyelamatkan kakaknya, Mina terjun ke air menggantikan Cheong. Kecantikan Mina memang tidak sebanding dengan para pengantin terdahulu. Tapi dia sudah tersapu ke Alam Roh. Kini Mina tak punya banyak waktu untuk menemukan Dewa Laut sebelum dirinya sendiri berubah menjadi arwah. Berbekal kemampuan mendongeng dan bantuan para arwah, Mina harus berhasil menemukan Dewa Laut.',
            penerbit: 'Elex Media Komputindo',
            tahun: '2023',
            penulis: 'Axie Oh',
            jumlahHalaman: '296',
            bahasa: 'Indonesia',
            gambar: 'assets/dewasa/TheGirlwhoFellBeneaththeSea.jpg',
            stok: '10',
            harga: '92000'
        },
        {
            id : 3,
            judul: 'Jejak Sejarah Di Dua Tanah Haram; Napak Tilas 85 Tempat Bersejarah Di Makkah Dan Madinah',
            sinopsis: "Jejak Sejarah di Dua Tanah Haram merupakan panduan menarik untuk beberapa tempat bersejarah yang ada di dua Tanah Haram, Mekah dan Madinah. Dari tempat kelahiran Islam hingga tempat peristirahatan terakhir Nabi Muhammad, buku ini akan membawa kita ke dalam perjalanan yang memikat melalui dua kota paling dihormati dalam Islam. Kita akan menjelajahi landmark ikonik seperti Kabbah, Hajar Aswad, dan Masjid al-Haram di Mekkah, serta Masjid Nabawi, pemakaman Al-Baqi, dan Gunung Uhud di Madinah. Kita juga akan menemukan tempat-tempat yang kurang dikenal seperti Masjid Al-Abwa, Masjid Quba, dan Gua Hira, masing-masing dengan kisah dan maknanya yang unik. Bagi yang sudah pernah ke Tanah Suci, buku ini akan menjadi pengingat kenangan suci. Bagi yang belum pernah ke Tanah Suci, buku ini akan menjadi langkah awal niat dan tekad untuk dapat berangkat ke Tanah Suci. Bagi seorang Muslim yang taat atau hanya tertarik pada sejarah dan budaya, Jejak Sejarah di Dua Tanah Haram harus dibaca. Dengan visual yang menakjubkan dan teks yang informatif, buku ini menawarkan pandangan menawan ke jantung tradisi Islam dan warisan abadi dari dua kota paling sucinya. Selamat membaca.",
            tahun: '2023',
            penulis: 'Mansya Aji Putra',
            penerbit: 'Elex Media Komputindo',
            jumlahHalaman: '296',
            bahasa: 'Indonesia',
            gambar: 'assets/dewasa/JejakSejarahDiDuaTanahHaram.jpg',
            stok: '14',
            harga: '104000'
        },
        {
            id : 5,
            judul: 'Etika Dan Moral Penegak Hukum Di Indonesia',
            sinopsis: "Fenomena penegak hukum yang terjerat kasus korupsi tidak sedikit. Hampir setiap tahunnya kasus yang menjerat penegak hukum ada. Indonesia merupakan negara hukum, yang seharusnya hukum menjadi panglima. Namun, hal itu hanyalah istilah belaka. Banyak penegak hukum yang terjerat kasus suap. Hakim, jaksa, advokat, bahkan sampai panitera di pengadilan pun ikut terlibat. Di tengah-tengah penegakan hukum negara yang sangat memprihatinkan, buku ini hadir menjawab fenomena tersebut. Buku ini mencakup berbagai etika profesi yang memang aktual untuk saat ini dikarenakan banyaknya terjadi fungsi jabatan yang jauh dari etika profesi. Sudut pandang etika dalam suatu profesi berbeda-beda. Oleh karena itu, setiap profesi terlebih dalam etika profesi penegak hukum, haruslah dibahas mendalam sehingga dapat memunculkan penegak hukum yang profesional serta tidak menyimpang dari etika profesi.Ketika keadilan dan penegakan hukum suatu negara berjalan sesuai dengan fungsinya tanpa pandang bulu, hal itu disebabkan oleh penegak hukum yang menjalankan etika profesinya secara benar. Etika merupakan ketentuan untuk menjadi penunjuk jalan bagi para penegak hukum untuk menghadirkan keadilan yang seadil-adilnya. Karenanya, buku ini hadir sebagai pengetahuan dasar mahasiswa hukum calon-calon penegak hukum yang memiliki integritas dan profesional dalam mengemban tugas profesinya. Selain itu, karya ini diharapkan memberikan pengkajian untuk pengembangan peradilan menjadi lebih baik.",
            tahun: '2023',
            penulis: 'A.salman Maggalatung',
            penerbit: 'Pt. Rajagrafindo Persada',
            jumlahHalaman: '178',
            bahasa: 'Indonesia',
            gambar: 'assets/dewasa/EtikaDanMoralPenegakHukumDiIndonesia.jpg',
            stok: '4',
            harga: '67150'
        },
        {
            id : 7,
            judul: '365 Renungan Dari Dunia Musik',
            sinopsis: "Buku renungan harian sepanjang tahun yang penuh dengan pelajaran berharga bagi pencinta musik sepanjang zaman. Melalui buku ini pembaca dapat belajar dari kesuksesan dan kegagalan para musisi seperti Paul McCartney, J.S. Bach, Duke Ellington, Steven Curtis Chapman, dan banyak lagi yang lain. Setiap tulisan menyoroti satu peristiwa atau satu pribadi dalam sejarah musik, kemudian pokok pemikirannya dihubungkan dengan kebenaran Kristiani mendasar yang akan membantu pembaca bertumbuh secara rohani.",
            tahun: '2014',
            penulis: 'A.salman Maggalatung',
            penerbit: 'Penerbit Satu-satu',
            jumlahHalaman: '391',
            bahasa: 'Indonesia',
            gambar: 'assets/dewasa/365RenunganDariDuniaMusik.jpg',
            stok: '13',
            harga: '16000'
        },
        {
            id : 9,
            judul: 'The Miracle Of Fokus',
            sinopsis: "Fokus adalah kunci untuk meningkatkan produktivitas dan konsentrasi, serta mengurangi gangguan dan kekhawatiran. Ketika kita fokus pada satu tugas, kita dapat menyelesaikannya dengan lebih cepat dan efisien, tanpa terganggu oleh hal lain. Selain itu, dengan fokus yang tinggi, kita bisa memperbaiki kualitas pekerjaan kita dan menghindari kesalahan yang mungkin terjadi ketika kita terlalu terburu-buru. Bila didefinisikan, fokus adalah titik pusat sesuatu. Cahaya yang terfokus berarti cahaya yang terpusat pada satu titik, seperti cahaya yang ditangkap oleh kaca pembesar dan menuju pada satu titik tertentu. Dalam pengertian yang lebih luas, fokus dimaknai sebagai upaya memusatkan perhatian. Saat Anda fokus pada sebuah gelas, itu berarti Anda sedang memusatkan perhatian Anda pada gelas.Namun yang perlu dipahami, orang yang sedang melihat sesuatu belum tentu sedang fokus. Anda dikatakan fokus hanya jika perhatian yang Anda miliki benar-benar terpusat pada sesuatu. Jadi, tidak sekadar melihat atau mendengar. Anda dikatakan fokus pada gelas jika perhatian Anda benar-benar terpusat pada gelas yang sedang Anda lihat. Saat Anda melihat sebuah gelas tapi perhatian Anda tidak tertuju pada gelas tersebut, maka Anda belum bisa dibilang sedang berfokus, melainkan sedang melamun saja. Fokus juga membantu kita memprioritaskan pekerjaan, sehingga kita dapat menyelesaikan tugas yang paling penting terlebih dahulu, dan menghindari menunda-nunda pekerjaan yang tidak penting. Dengan demikian, fokus merupakan salah satu keajaiban yang sangat penting untuk meningkatkan produktivitas kita.",
            tahun: '2023',
            penulis: 'Sony Adams',
            penerbit: 'Anak Hebat Indonesia',
            jumlahHalaman: '122',
            bahasa: 'Indonesia',
            gambar: 'assets/dewasa/TheMiracleOfFokus.jpg',
            stok: '3',
            harga: '42500'
        },
    ],
    anakanak: [
        {
            id : 2,
            judul: 'ENSIKLOPEDIA ANAK CERDAS : OLAHRAGA',
            sinopsis: 'Cro-Magnon, merupakan nenek moyang sejak 35.000 tahun lalu. Berlari lebih cepat daripada Usain Bolt, juara dunia lari 100 m! Apakah kamu tidak percaya? Kini, kamu hidup di zaman modern yang semuanya sudah serba praktis, sama halnya dengan olahraga. ternyata olahraga sudah ada sejak zaman dulu. Dan olahraga berkembang dari zaman dulu hingga zaman sekarang. Banyak terjadi perubahan. Kira-kira bagaimana awal mula olahraga di sekitar kita, ya?Penasaran, kan? Yuk, kita pelajari bersama!',
            tahun: "2019",
            penulis: 'Geraldine Maincent',
            penerbit: 'Bhuana Ilmu Populer',
            jumlahHalaman: "96",
            bahasa: 'Indonesia',
            gambar: 'assets/anak-anak/EnsiklopediaAnakCerdasOlahraga.jpg',
            stok: '7',
            harga: '121500'
        },
        {
            id : 4,
            judul: 'KISAH EMPAT SAHABAT SUPER: MEMBEBASKAN PENYU',
            sinopsis: 'Bukuinimenceritakankisahkeempatsahabat. Merekaadalah Orangutan, Harimau, Cendrawasih, dan Komodo. KeempatsahabattersebutmencobamenolongseekorIbuPenyu yang tersangkutsampah di pantai.',
            tahun: "2017",
            penulis: 'VALERINA DANIEL',
            penerbit: 'DAR',
            jumlahHalaman: "40",
            bahasa: 'Indonesia',
            gambar: 'assets/anak-anak/KISAHEMPATSAHABATSUPERMEMBEBASKANPENYU.jpeg',
            stok: '8',
            harga: '35000'
        },
        {
            id : 6,
            judul: 'Komik Tajwid untuk anak',
            sinopsis: 'Komik anak menjadi cara menyenangkan, menarik, dan mudah untuk mengajarkan nilai-nilai Islam dan nilai-nilai moral pendidikan kepada anak',
            tahun: "2022",
            penulis: 'Lina Herlina',
            penerbit: 'Gema Insani',
            jumlahHalaman: "72",
            bahasa: 'Indonesia',
            gambar: 'assets/anak-anak/komiktajwid.jpg',
            stok: '12',
            harga: '81000'
        },
        {
            id : 8,
            judul: 'Seri Buku Toleransi: Prasangka Moka',
            sinopsis: "Moka kebingungan! Perjalanan ke rumah nenek yang awalnya menyenangkan seketika menjadi beban ketika Moka lupa arah jalan. Ia terus melangkah tanpa tahu tujuan, sampai hari mulai gelap dan matahari tenggelam perlahan. Haruskah Moka menerima bantuan dari binatang lain di hutan? Apa benar perangai mereka seperti yang sering dikabarkan?",
            tahun: "2018",
            penulis: 'Sekar Sosronegoro',
            penerbit: 'Buah Hati',
            jumlahHalaman: "32",
            bahasa: 'Indonesia',
            gambar: 'assets/anak-anak/SeriBukuToleransiPrasangkaMoka.jpeg',
            stok: '2',
            harga: '55000'
        },
        {
            id : 10,
            judul: 'Legenda Dongeng Nusantara: Keong Mas',
            sinopsis: 'Alkisah, ada dua putri raja yang tidak akur. Salah seorang putri mempunyai rasa iri hati karena saudaranya akan menikah dengan calon suami yang tampan  nan rupawan. Dongeng ini mengajarkan kita untuk tidak memunyai rasa iri, karena iri dapat menjerumuskan kita untuk melakukan hal-hal buruk lainnya, seperti salah seorang tuan putri dalam kisah ini.',
            tahun: "2020",
            penulis: 'Kak Adam',
            penerbit: 'Playground',
            jumlahHalaman: 	"28",
            bahasa: 'Indonesia',
            gambar: 'assets/anak-anak/LegendaDongengNusantaraKeongMas.jpg',
            stok: '5',
            harga: '26775'
        },
    ]
};

